import "../../globals.css";
import React from "react"
import Header from "../../../components/Header";
import Navbar from "../../../components/Navbar";
import ListPosts from "../../../components/ListPosts";
import Post from "../../../components/Article";
import Article from "../../../components/Article";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossOrigin="anonymous" /> */}
      </head>
      <body>
        <div className="container-fluid d-flex">
          <div style={{ width: "80%" }}>
            <Header/>
            <Navbar/>
            <Article/>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
