import "../globals.css";
import React from 'react';
import dynamic from "next/dynamic";
const Header = dynamic(()=>import("../../components/Header"),{ssr:false})
const Footer = dynamic(()=>import("@/components/Footer"),{ssr:false})

export const metadata = {
  title: 'CanCook',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossOrigin="anonymous" /> */}
      </head>
      <body>
        <div className="container-fluid">
          <div>
            <Header/>
            {children}
            <Footer/>
          </div>
        </div>
      </body>
    </html>
  )
}
